feat(LEARN-63): finished registration page
learn-track/learnTrack pull request #113
Opened 2024-05-02 18:06 UTC by kieranslost

2024-05-02 18:33 UTC, deepspace1000 requested changes

2024-05-02 18:33 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +    const [errorMessage, setErrorMessage] = useState('Registration fehlgeschlagen');//ich will den error message zurückbekommen, weis aber noch nicht genau wie oder ob das geht
use react-hook-forms: https://react-hook-form.com/

2024-05-02 18:33 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +        <Grid container sx={{ flexGrow: 1, maxWidth: '100%', overflow: 'hidden' }}>
use styled components

2024-05-02 18:33 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +                        <Typography level="h2" component={'h2'} sx={{ position: 'absolute', fontSize: '45px', marginTop: '5vh', textAlign: 'center'}}>
you don't need `component={'h2'}`

2024-05-02 18:33 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +                <Grid xs={12} sx={{ position: 'absolute' }}>
try not to use absolute

2024-05-02 18:33 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +  margin: 10vh 20vw;
don't use vh either rem or px

2024-05-02 18:33 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +                        <RegisterForm></RegisterForm>
```suggestion
                        <RegisterForm/>
```

2024-05-02 18:39 UTC, kieranslost commented on frontend/src/pages/RegisterPage.tsx
> +        <Grid container sx={{ flexGrow: 1, maxWidth: '100%', overflow: 'hidden' }}>
Das isch en grid ding, macht es wück sin da en styled component zbenutze?

2024-05-02 18:39 UTC, kieranslost commented on frontend/src/pages/RegisterPage.tsx
> +                        <Typography level="h2" component={'h2'} sx={{ position: 'absolute', fontSize: '45px', marginTop: '5vh', textAlign: 'center'}}>
gemacht 👍

2024-05-02 18:40 UTC, kieranslost commented on frontend/src/pages/RegisterPage.tsx
> +  margin: 10vh 20vw;
changed everything to px 👍

2024-05-03 05:51 UTC, deepspace1000 requested changes
to exclude the header you need to add the register path to `App.tsx` just like the login page.
to fix formatting (prettier) errors run `yarn format` (thats why the pipeline fails).

2024-05-03 05:51 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +      <form onSubmit={handleSubmit(onSubmit)}>
Thats not quite right just yet. Also i don't think it would work

2024-05-03 05:51 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  const inputBackgroundColor = showInputError ? '#fadada' : 'rgba(137, 218, 213, 0.5)';
remove this and use joy ui color theme with `danger`.

2024-05-03 05:51 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +            <Input
all those inputs have the same sx. make a styled component.

2024-05-03 05:53 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +                <Grid xs={12} sx={{ position: 'absolute' }}>
Try not to use it anywhere in your code

2024-05-03 05:55 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +        <Grid container sx={{ flexGrow: 1, maxWidth: '100%', overflow: 'hidden' }}>
Oh i see. I am not that big of a fan of the joy ui Grid. you can leave it or make a styled div acting like a grid.

2024-05-03 16:52 UTC, deepspace1000 requested changes
FYI, the branch naming goes `feat/LERN-TicketNumber` (have a look at the tutorials in the docs folder) but its okay for now just for the future 😉.

2024-05-03 16:52 UTC, deepspace1000 commented on frontend/src/App.tsx
> +  const showHeader: boolean = location.pathname !== '/login' && location.pathname !== '/register';
i don't think that works 😅. `||`

2024-05-03 16:52 UTC, deepspace1000 commented on frontend/src/App.tsx
> +  const showHeader: boolean = location.pathname !== '/login' && location.pathname !== '/register';
Or no your right it's not shown but now its never shown

2024-05-03 16:52 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  //const inputBackgroundColor = showInputError ? 'danger' : 'rgba(137, 218, 213, 0.5)';
delete

2024-05-03 16:52 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  const onRegister = async (data: Inputs) => {
I would suggest `handleSubmit` as it is a handler and it handles the submit.

2024-05-03 16:52 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +const NameInputField = styled('input')<{ showInputError: boolean }>`
`styled(Input)` now your using the HTML Input if you want to use a you UI component you can omit the `` and just write the component name.

2024-05-03 16:52 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  &:focus {
I guess if you use the JoyUi Input you can omit the error styles and use the `FormControl` error

2024-05-03 17:39 UTC, kieranslost commented on frontend/src/App.tsx
> +  const showHeader: boolean = location.pathname !== '/login' && location.pathname !== '/register';
ima be honest han au nöd denkt, dass das funktioniert. Han am afang au mit `||` probiert

2024-05-05 19:47 UTC, deepspace1000 requested changes
Looks a lot better now 😃

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  //const [showInputError, setShowInputError] = useState(false);
delete

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  const [showDoublePasswordError, setShowDoublePasswordError] = useState(false);
probably more like `showPasswordNotMatchError` or something like that

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  const [showEmailError, setShowEmailError] = useState(false);
`showInvalidEmailError` ?

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  const onRegister = async (data: Inputs) => {
would still rename it.

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +      if (password !== confirmPassword) {
put those checks in separate const functions at the end of the file: 
`const CheckPasswordMatch = (firstPassword:string, secondPassword:string) => {}` or similar

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +      // checks if the password and the control password matches
we normally don't comment code.

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +      // checks if the password and the control password matches
If you put in functions and give them good names they are explaining what the code does without a comment. so function name == comment.

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +    <Grid xs={11} sx={{ marginTop: '65px' }}>
would get rid of this grid to and use a css grid. Just so we do it consistently

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +                <StyledFormLabel>Vorname*</StyledFormLabel>
```suggestion
                <StyledFormLabel>Vorname: *</StyledFormLabel>
```

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +              </FormControl>
I would add a `FormHelperText` for all inputs and show then on error: 
`Vorname muss ausgefüllt werden` or similar.

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +                <FormHelperText sx={{ color: '#C41C1C' }}>*Pflichtfelder müssen gesetzt sein</FormHelperText>
I would put this for each filed individually. also you could put different errors depending on the error like password input or mail input

2024-05-05 19:47 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +        sx={{ backgroundColor: '#f6e0e0' }}
color danger should be enough.

2024-05-05 19:53 UTC, kieranslost commented on frontend/src/components/RegisterForm.tsx
> +      // checks if the password and the control password matches
fair

2024-05-05 19:57 UTC, kieranslost commented on frontend/src/components/RegisterForm.tsx
> +                <FormHelperText sx={{ color: '#C41C1C' }}>*Pflichtfelder müssen gesetzt sein</FormHelperText>
yes master 😞  xD

2024-05-05 20:44 UTC, deepspace1000 requested changes
Just a few more things...

2024-05-05 20:44 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
>    const [errorMessage, setErrorMessage] = useState('Registration fehlgeschlagen.');
I would remove this and show only this error in the Snackbar. The other errors should be displayed on the input fields where they originate.

2024-05-05 20:44 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
>          <Grid sx={{ display: 'flex', justifyContent: 'center', flexWrap: 'wrap' }}>
One more grid 😂

2024-05-05 20:44 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +              <FormControl error={errors.firstname !== undefined}>
try `!!errors.firstname` looks a bit nicer then allways checking for `undefined`

2024-05-05 20:44 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +                  <FormHelperText sx={{ color: '#C41C1C' }}>Vorname muss ausgefüllt werden</FormHelperText>
Do should not need the color. it should automatically use the `danger` color from the `FormControl error`

2024-05-05 20:44 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
>      try {
why are you using a `try`? try to do it without.

2024-05-05 20:48 UTC, kieranslost commented on frontend/src/components/RegisterForm.tsx
>      try {
i got told to do it this way 😔, aber ez

2024-05-07 17:36 UTC, deepspace1000 requested changes

2024-05-07 17:36 UTC, deepspace1000 commented on frontend/src/pages/RegisterPage.tsx
> +    <Grid container sx={{ flexGrow: 1, maxWidth: '100%', overflow: 'hidden' }}>
remove these `Grid`s also.

2024-05-07 17:36 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +    await UserRessourceService.register({ firstname, middlename, lastname, email, password })
Do this with a useMutation (see Login Form)

2024-05-07 17:36 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +  const [errorMessage, setErrorMessage] = useState('Registration fehlgeschlagen');
remove this and also all snackbar calls except when an error occures in the backend. 
create 2 snackbars, 1 for `Fehler bei der Registrierung` and 1 for `E-Mail wurde bereits registriert` depending on the error code you receive from the backend.

2024-05-07 17:36 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +      password.replace(/[^0-9]/g, '') === ''
try to do this with a regex like in the backend.

2024-05-07 17:36 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +    if (!email.includes('@')) {
this is not enough. use the regex we use in the backend.

2024-05-07 17:36 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +                {errors.firstname && <FormHelperText color={'danger'}>Vorname muss gesetzt sein</FormHelperText>}
you don't need the color prop. this is done by the `FormControl`.

2024-05-12 15:06 UTC, deepspace1000 requested changes

2024-05-12 15:06 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +const useRegisterMutation = () => {
See `LoginForm.tsx`

2024-05-15 06:21 UTC, deepspace1000 reviewed
Maybe you could implement the tooltip i suggested and make a quick test if it still works this way. 
If you have a question about something write a comment and i will try to explain it as best as i can 🙃.

2024-05-15 06:21 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +                  {/*@Todo I would an info icon with a tooltip to this error where we can put in the specifications.
This would be my suggestion. Maybe you can do a "simple" version of it. just a Tooltip without something big and fancy.

2024-05-15 06:21 UTC, deepspace1000 commented on frontend/src/components/RegisterForm.tsx
> +    onError,
FYI: I removed all the async try and catch part as it is done automatically by useMutation.

2024-05-15 20:49 UTC, deepspace1000 approved these changes
very nice 🙃

2024-05-15 20:52 UTC, merged