feat(LERN-40): added Header and Atom caching of the whoami Endpoint
learn-track/learnTrack pull request #117
Opened 2024-05-11 20:02 UTC by Quintexxx

Maybe you will see a warning bc of the active class, joy ui adds the class to the active page automatically so the IDE is wrong

2024-05-12 15:20 UTC, deepspace1000 requested changes
the conflicts are there because your Branch is out of date with the master. rebase the master on this branch and merge the files with conflicts.

2024-05-12 15:20 UTC, deepspace1000 commented on frontend/src/App.tsx
> +        <Route path={'/classes'} element={<ClassPage />} />
In the backend we use `Grade` instead of `class` because the word class could lead to problems... I would suggest we do the same in the Frontend. I know i wasn't consistent writing the user Stories...

2024-05-12 15:20 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +              {whoami.user.userRole == 'ADMIN' ? <AdminUserMenu /> : <div />}
```suggestion
              {whoami.user.userRole == 'ADMIN' && <AdminUserMenu /> }
```

2024-05-12 15:20 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +              {whoami.user.userRole == 'ADMIN' ? <AdminUserMenu /> : <div />}
Like this we are displaying the userMenu when he is an admin and don't do anything when he isn't

2024-05-12 15:20 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +  window.location.href = '/login';
Do you think it is possible to do something like a `hard refresh`? I would like to clean up as much as possible but `location.href` is already HTML navigation so it might be good enough. But if you find something would be nice.

2024-05-12 15:20 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +  font-family: Montserrat, sans-serif;
I would use the same Font over the whole application. So if you want to use this put it in the theme.ts file and use it everywhere.
Because using different Font Families makes it look inconsistent.

2024-05-12 15:20 UTC, deepspace1000 commented on frontend/src/components/LoginForm.tsx
> +const SubmitButton = styled(Button)`
are these styles necessary because of the Style overrides in the theme.ts?

2024-05-17 08:42 UTC, Quintexxx commented on frontend/src/components/Header.tsx
> +  window.location.href = '/login';
I've personally looked into it, i think removing the token and changing the site with the location.href is good enough

2024-05-17 08:48 UTC, Quintexxx commented on frontend/src/components/LoginForm.tsx
> +const SubmitButton = styled(Button)`
Yes ive decided that my special Submit is way too fancy and it would majorly change the entire theme. It affects dropdowns, all types of buttons and way more.

Maybe in the future we can make a componont for it but i've intended to use this style for only submit buttons as of right now.

2024-05-17 08:51 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +  window.location.href = '/login';
Sounds good 👍

2024-05-17 09:40 UTC, deepspace1000 reviewed
Regarding the design. i would reduce the height of the header about 50% and make the logo smaller.

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +          <LogoDark></LogoDark>
couldn't you do a `display: flex` on the HeaderContainer and do `justifyContent: spaceBetween` and the omit the LeftItems and RightItems and just use the MenuItems?

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +        <MenuItems>
```suggestion
        <NavigationItems>
```

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +        <RightItems>
Same as `LeftItems`

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +            <UserMenuDropdown>
```suggestion
            <UserMenu>
```

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +              <MenuItemTopDescription>
```suggestion
              <UserDetails>
```

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +              {whoami.user.userRole == 'STUDENT' ? <StudentUserMenu /> : <div />}
```suggestion
              {whoami.user.userRole == 'STUDENT' && <StudentUserMenu />}
```

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +              {whoami.user.userRole == 'STUDENT' ? <StudentUserMenu /> : <div />}
for all menus

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/components/Header.tsx
> +function AdminUserMenu() {
I would remove this completely as we don't like dead code. We can just write it again if we need it in the Future but when we won't need it we also won't delete it.

2024-05-17 09:40 UTC, deepspace1000 commented on frontend/src/customTheme.ts
> +  fontFamily: {
nice

2024-05-17 11:50 UTC, Quintexxx commented on frontend/src/App.tsx
>        </Routes>
yes sir

2024-05-17 12:24 UTC, deepspace1000 approved these changes
I hope you did a good job 🙃

2024-05-17 12:27 UTC, merged