feat(LERN-67): added function to create Grade and added the admin package
learn-track/learnTrack pull request #119
Opened 2024-05-13 21:02 UTC by A1eeee

2024-05-13 21:16 UTC, A1eeee commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeDto.kt
> +public data class GradeDto(
So sonarcloud says there is no Code coverage.
If you still remind we talked about this that i still need both of the Dto and I already have planned to use the "GradeDto" for the task 70.

2024-05-13 21:19 UTC, A1eeee commented on backend/src/main/kotlin/ch/learntrack/backend/security/UserAccessAuthorizer.kt
>      public fun isUser(myUserDetails: LearnTrackUserDetails): Boolean = myUserDetails.username == "testuser@gmail.com"
Somehow sonarcloud thinks this line of code is new and uncovered.

2024-05-14 19:15 UTC, deepspace1000 requested changes
I would say one of your next top priorities should be to implement the RoleBased access control. The longer we wait the more complicated the change will be.

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/AdminRessource.kt
> +    public fun createGrade(@RequestBody createGradeDto: CreateGradeDto): Grade = gradeService.createGrade(
i would create a GradeRessource file in the admin->grade package. 
Additionally add a fine based access control by sending the school id over a Request Param `@RequestParam` in the same place as the `@RequestBody` and then check if the user has access to the school. 
Maybe we can have a look at this together.

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeDto.kt
> +public data class GradeDto(
Its okay for now. Maybe in the future when there is more code its not good practice to write code you may use later because sometimes you don't and the forget it and we get dead code. But at the moment we can leave it.

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeService.kt
> +    public override fun mapToDto(pojo: Grade): GradeDto = GradeDto(
Same as above.

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeService.kt
> +        if (gradeDao.fetchBySchoolId(createGradeDto.schoolId).any { it.name.trim() == createGradeDto.name.trim() }) {
you don't need to do this with `.any` just write a query which gets a grade by `shoolId` and by `name` if the result is notNull throw an error.

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/security/UserAccessAuthorizer.kt
>      public fun isUser(myUserDetails: LearnTrackUserDetails): Boolean = myUserDetails.username == "testuser@gmail.com"
I just added this as an example but its not doing anything. you can remove this function. also add the other function i requested above here the `hasUserAccessToSchoolAsAdmin` or something like this

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/security/UserAccessAuthorizer.kt
> +    public fun isAdminUser(myUserDetails: LearnTrackUserDetails): Boolean = myUserDetails.user.userRole ==
nice

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/security/UserAccessAuthorizer.kt
> +    public fun isAdminUser(myUserDetails: LearnTrackUserDetails): Boolean = myUserDetails.user.userRole ==
do the other function like this, but you will need to write an additional db query

2024-05-14 19:15 UTC, deepspace1000 commented on backend/src/test/kotlin/ch/learntrack/backend/admin/AdminSecurityIntegrationTest.kt
> +}
Try to write additional tests with trying to access the `/admin` endpoint as teacher and student.

2024-05-14 19:21 UTC, A1eeee commented on backend/src/main/kotlin/ch/learntrack/backend/admin/AdminRessource.kt
> +    public fun createGrade(@RequestBody createGradeDto: CreateGradeDto): Grade = gradeService.createGrade(
Okay, do you have time tomorrow to look at this?

2024-05-17 08:47 UTC, A1eeee commented on backend/src/test/kotlin/ch/learntrack/backend/admin/grade/GradeIntegrationTest.kt
> +    @Test
New Test: Admin user can't be allowed to create a school when he is not related to that school.

2024-05-20 09:15 UTC, deepspace1000 requested changes

2024-05-20 09:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeBeans.kt
> +    bean<GradeRessource>()
For new Files use Resource instead of Ressource.

2024-05-20 09:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeQueries.kt
> +public fun GradeDao.isGradeAlreadyExistingInSchool(createGradeDto: CreateGradeDto): Boolean = ctx()
Queries should not return booleans. they are for fetching data and always return a Object. the check if it is null or not should be done in the Service class

2024-05-20 09:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/security/UserAccessAuthorizer.kt
>      public fun isAdminUser(myUserDetails: LearnTrackUserDetails): Boolean = myUserDetails.user.userRole ==
Actually i am not sure if this works at all, because i don't think we store the userRole in the LearnTrackUserDetails. But you can leave it and then remove it when we get role based access control

2024-05-20 09:15 UTC, deepspace1000 commented on backend/src/test/kotlin/ch/learntrack/backend/admin/AdminSecurityIntegrationTest.kt
> +                    .path("$ADMIN_ROOT_URL/grade/createGrade")
Make a TODO comment somewhere that the paths will have to shortend to just $ADMIN_ROOT_URL when we get role based

2024-05-20 09:15 UTC, deepspace1000 commented on backend/src/test/kotlin/ch/learntrack/backend/admin/grade/GradeIntegrationTest.kt
> +    fun `should not be able to create grade if the admin is not part of the school` () {
`if admin not assigned to school`

2024-05-20 09:15 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeRessource.kt
> +        "@UserAccessAuthorizer.hasUserAccessToSchoolAsAdmin(#root.authentication.principal, #schoolId)",
We don't actually check here if he has access to school 'as Admin' but just if he has. the admin check was made above. So i would rename it to `hasUserAccessToSchool` and if i am not wrong you can use it again for teachers and students

2024-05-20 18:29 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-05-20 18:39 UTC, deepspace1000 commented on backend/src/test/kotlin/ch/learntrack/backend/admin/AdminSecurityIntegrationTest.kt
> +                    .path("$ADMIN_ROOT_URL/grade/createGrade")
where is the comment`

2024-05-20 18:41 UTC, A1eeee commented on backend/src/test/kotlin/ch/learntrack/backend/admin/AdminSecurityIntegrationTest.kt
> +                    .path("$ADMIN_ROOT_URL/grade/createGrade")
backend/src/main/kotlin/ch/learntrack/backend/admin/AdminBeans.kt

I thought you meant for all the Admin paths and not only the test ones.

2024-05-20 18:56 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeQueries.kt
> +public fun GradeDao.isGradeAlreadyExistingInSchool(createGradeDto: CreateGradeDto): Grade? = ctx()
```suggestion
public fun GradeDao.fetchByNameAndSchoolId(createGradeDto: CreateGradeDto): Grade? = ctx()
```
Or similar. a function name starting with `is` returns a boolen. if you write a function returning a boolen and it isn't called `is` diktat and detekt won't like it.

2024-05-20 18:56 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeQueries.kt
actually, for the moment i would keep all queries in the `persistence` package in the root. as we mostly will be able to reuse queries for different users and it gets to complicated when we start splitting up even the queries files. So for the moment i would keep them all in the root.

2024-05-20 18:56 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeQueries.kt
Also these are just extension function for a Dao Object. So it makes sense to keep them all in the same file.

2024-05-20 18:56 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeService.kt
> +                "Grade with name ${createGradeDto.name} already exists for school with id ${createGradeDto.schoolId}",
```suggestion
                "Grade ${createGradeDto.name} already exists for school ${createGradeDto.schoolId}",
```
as these comments only we can see in the logs on the server and therefore keep them short and simple while keep important information

2024-05-20 18:56 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/AdminBeans.kt
> +// TODO: Add path endpoints to ADMIN_ROOT_URL when role bases access control is implemented
😂 i guess you can delete that again

2024-05-20 19:12 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-05-20 19:13 UTC, deepspace1000 approved these changes
Nice now lets get to the role based access control 🥳

2024-05-20 19:28 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-05-20 19:31 UTC, merged