feat(LERN-92): implemented user list for getGrades endpoint (admin)
learn-track/learnTrack pull request #137
Opened 2024-05-31 13:42 UTC by A1eeee

Fix: fixed getTeachers query for admins

2024-06-03 17:31 UTC, deepspace1000 requested changes

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeService.kt
> +    public fun getGrades(schoolId: UUID): GradeDetailsDto = GradeDetailsDto(
```suggestion
    public fun getAllGradesForSchool(schoolId: UUID): GradeDetailsDto = GradeDetailsDto(
```

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeService.kt
> +        return gradeService.mapToDto(grade)
why are you returning the grade here? Is there any specific reason?

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeBeans.kt
>      bean<GradeResource>()
I would probably rename the Resource to `AdminGradeResource` as well.

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeDetailsDto.kt
> +    val grades: List<GradeDto>,
That shouldn't be a list.

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeDetailsDto.kt
> +    val users: List<UserDto>,
```suggestion
    val students: List<UserDto>,
```

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeResource.kt
> +    public fun getGrades(@RequestParam schoolId: UUID): GradeDetailsDto =
```suggestion
    public fun getGrades(@RequestParam schoolId: UUID): List<GradeDetailsDto> =
```

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/GradeResource.kt
> +    public fun createGrade(@RequestParam schoolId: UUID, @RequestBody createGradeDto: CreateGradeDto): GradeDto =
I don't think we need/want to return the grade again. the frontend has to refetch anyway after creating a grade to update the grade list.

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/teacher/TeacherBeans.kt
>      bean<TeacherResource>()
Maybe also rename this to `AdminTeacherResource`?

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/grade/GradeDto.kt
> +public data class CreateGradeDto(
Maybe move this to the admin grade package...  as we won't need it again for something else?

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/grade/GradeService.kt
> +    public fun getGradeByNameAndSchoolId(createGradeDto: CreateGradeDto): Grade? = gradeDao.fetchByNameAndSchoolId(
specifically give the 2 parameters `name` and `SchoolId`. in anyway it shouldn't be named `create`

2024-06-03 17:31 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/grade/GradeService.kt
> +    public fun isGradeNameExistingInThisSchool(createGradeDto: CreateGradeDto): Boolean =
same here give the parameters explicitly.

2024-06-04 21:04 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-12 16:34 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeResource.kt
> +    }
```suggestion
    public fun createGrade(@RequestParam schoolId: UUID, @RequestBody createGradeDto: CreateGradeDto) = adminGradeService.createGrade(
            createGradeDto,
        )
    
```

2024-06-12 16:34 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeService.kt
> +        if (gradeService.isGradeNameExistingInThisSchool(createGradeDto.schoolId, createGradeDto.name)) {
```suggestion
        if (gradeService.isGradeExistingInSchool(createGradeDto.name, createGradeDto.schoolId)) {
```

2024-06-12 16:34 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeService.kt
> +            throw LearnTrackConflictException("Grade with name ${createGradeDto.name} already exists in this school")
```suggestion
            throw LearnTrackConflictException("Grade with name ${createGradeDto.name} already exists in school ${createGradeDto.shoolId}")
```

2024-06-12 16:34 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/grade/GradeService.kt
> +    public fun isGradeNameExistingInThisSchool(schoolId: UUID, name: String): Boolean =
```suggestion
    public fun isGradeExistingInSchool(name: String, schoolId: UUID): Boolean =
```

2024-06-12 16:34 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeResource.kt
> +    public fun getAllGradesForSchool(@RequestParam schoolId: UUID): List<GradeDetailsDto> =
maybe `getAllGradesWithDetailsBySchoolId`? 
Definitely use `BySchoolId`.
Maybe use `GradesWithDetails`.

2024-06-12 17:47 UTC, A1eeee commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeResource.kt
> +    }
The problem is if we use it that way I need to specify a :Unit and sadly the diktatCheck doesn't like that he says that is unnecessary and if I don't use that I get an error from the Kotlin side that we need to use :Unity.

That's why we didn't use your suggestion if I remember correctly
 backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserResource.kt

2024-06-12 18:56 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/admin/grade/AdminGradeResource.kt
> +    }
You can try to remove that from the diktat config in that case.

2024-06-12 19:18 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-12 19:21 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-12 19:40 UTC, deepspace1000 reviewed
Are there any test yet?

2024-06-12 19:40 UTC, deepspace1000 commented on backend/detekt.yml
🙃

2024-06-12 19:44 UTC, A1eeee commented
> Are there any test yet?

I mean that task is a fix/enhancement task for the other two tasks that I've done before that one.

2024-06-12 20:46 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/login-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/3dc17e5884542fc274013e6fa12162f19f2949d1b600a1749ab093a1017c9265.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/3eee50600ee883a3d10b2e51859a088bc3b5182ad173f6f8bd6a68fc5fdac4a4.png) |

2024-06-13 10:16 UTC, deepspace1000 reviewed
FYI you can enhance your commit messages a bit e.g you last commit could be: `added tests for admin grade endpoints` or something like that. 
The message `implemented requested changes` can be used when there is nothing really to describe what you did but should not be used if possible.

2024-06-13 10:16 UTC, deepspace1000 commented on backend/src/test/kotlin/ch/learntrack/backend/admin/grade/GradeIntegrationTest.kt
add some more test data like second grade in a different school, which shouldn't be returned. 
add a teacher to 2 grades in 2 schools and check if he is returned in both. ect.

2024-06-13 17:56 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/login-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/3dc17e5884542fc274013e6fa12162f19f2949d1b600a1749ab093a1017c9265.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/3eee50600ee883a3d10b2e51859a088bc3b5182ad173f6f8bd6a68fc5fdac4a4.png) |

2024-06-13 18:01 UTC, deepspace1000 approved these changes
LGTM

2024-06-13 18:04 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-13 18:06 UTC, merged