feat(LERN-84): implemented teacher dashboard
learn-track/learnTrack pull request #138
Opened 2024-05-31 14:02 UTC by kieranslost

2024-06-03 17:49 UTC, deepspace1000 requested changes

2024-06-03 17:49 UTC, deepspace1000 commented on frontend/src/state/api/teachers.ts
> +export const useTeachersQuery = (schoolId: string) => {
```suggestion
export const useGetTeachersForSchoolQuery = (schoolId: string) => {
```
`useTeachersQuery` is a bit to generic

2024-06-03 17:49 UTC, deepspace1000 commented on frontend/src/pages/TeacherPage.tsx
>      <>
not needed

2024-06-03 17:49 UTC, deepspace1000 commented on frontend/src/components/TeacherTable.tsx
> +        <Sheet sx={{ height: 500, overflow: 'auto', backgroundColor: '#f6fbfa' }}>
I think you don't need the sheet here. you can use the div for all this stuff.

2024-06-03 17:49 UTC, deepspace1000 commented on frontend/src/pages/TeacherPage.tsx
> +        <Grid container spacing={2} sx={{ flexGrow: 1 }}>
i would still go with css grid 🙃

2024-06-03 17:49 UTC, deepspace1000 commented on frontend/src/pages/TeacherPage.tsx
> +          <Grid xs={6} margin={0}>
here too

2024-06-03 17:49 UTC, deepspace1000 commented on frontend/src/pages/TeacherPage.tsx
> +      <Box
You could create a component `ContentSection` which would have this fixed with and so you can reuse it for every page.

2024-06-03 17:49 UTC, deepspace1000 commented on frontend/src/pages/TeacherPage.tsx
> +            <Typography level="h3" component={'h2'} margin={0}>
```suggestion
            <Typography level="h3" margin={0}>
```

2024-06-04 09:00 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-04 16:49 UTC, deepspace1000 reviewed
Already looks a lot better now 😃

2024-06-04 16:49 UTC, deepspace1000 commented on frontend/src/pages/TeacherPage.tsx
> +        <Button style={{ float: 'right' }}>Lehrer hinzufügen</Button>
could you use something like `alignSelf: right` or `alignSelf: flexEnd` ?

2024-06-04 16:49 UTC, deepspace1000 commented on frontend/src/components/TeacherTable.tsx
> +const TableBody = styled('td')`
```suggestion
const TableData = styled('td')`
```

2024-06-04 16:49 UTC, deepspace1000 commented on frontend/src/components/TeacherTable.tsx
> +const TableBody = styled('td')`
```suggestion
const TableData = styled('td')`
```

2024-06-04 16:49 UTC, deepspace1000 commented on frontend/src/components/TeacherTable.tsx
> +const TableBody = styled('td')`
```suggestion
const TableData = styled('td')`
```

2024-06-07 12:15 UTC, kieranslost commented on frontend/src/pages/TeacherPage.tsx
> +        <Button style={{ float: 'right' }}>Lehrer hinzufügen</Button>
turns out since i used "space-between" i dont need this code anyways

2024-06-07 12:20 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-07 18:34 UTC, deepspace1000 commented on frontend/src/pages/TeacherPage.tsx
> +        <Button style={{ float: 'right' }}>Lehrer hinzufügen</Button>
Well thats even better 😄

2024-06-07 18:35 UTC, deepspace1000 reviewed
Nice now fix the sonar issue und you can merge

2024-06-07 18:45 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/9594ffbab56afe91ef9ce50c3c2dfcd849632e6fecb6fcedfc3ec7e8e9b7b578.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/012d0289f647d46ad5d7f553efc5e9e0386134b06aab2ffc5f60af47eb6ef9fa.png) |

2024-06-07 18:51 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/9594ffbab56afe91ef9ce50c3c2dfcd849632e6fecb6fcedfc3ec7e8e9b7b578.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/012d0289f647d46ad5d7f553efc5e9e0386134b06aab2ffc5f60af47eb6ef9fa.png) |

2024-06-07 18:53 UTC, deepspace1000 approved these changes

2024-06-14 07:43 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-14 07:45 UTC, merged