feat(LERN-90): implemented redirect to grades page
learn-track/learnTrack pull request #139
Opened 2024-05-31 15:14 UTC by kieranslost

I kept the old version in the code incase someone wants to use it

2024-06-03 17:51 UTC, deepspace1000 requested changes
Nice 🥳

2024-06-04 09:09 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/9594ffbab56afe91ef9ce50c3c2dfcd849632e6fecb6fcedfc3ec7e8e9b7b578.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/012d0289f647d46ad5d7f553efc5e9e0386134b06aab2ffc5f60af47eb6ef9fa.png) |

2024-06-04 16:36 UTC, deepspace1000 commented on frontend/src/App.tsx
> +        {/*<Route path={'/'} element={<LandingPage />} />*/}
I think the LandingPage isn't use anymore is it? If not you can delete it.

2024-06-07 12:22 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-07 16:33 UTC, deepspace1000 approved these changes

2024-06-07 16:36 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/9594ffbab56afe91ef9ce50c3c2dfcd849632e6fecb6fcedfc3ec7e8e9b7b578.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/012d0289f647d46ad5d7f553efc5e9e0386134b06aab2ffc5f60af47eb6ef9fa.png) |

2024-06-07 16:38 UTC, merged