feat(LERN-68): user can now create grades
learn-track/learnTrack pull request #150
Opened 2024-06-18 21:31 UTC by kieranslost

2024-06-20 10:18 UTC, deepspace1000 requested changes
Just had a short look.
move the modal to its own file and afterwards i will give you a propper review. also run the formatter 🙃

2024-06-20 10:18 UTC, deepspace1000 commented on frontend/src/pages/GradePage.tsx
> +    type CreateGradeDto,
I guess you've don that manually? you should not need write the imports manually. if you do you probably did something wrong. 
I'm talking about the type import, i've never seen that 🤔

2024-06-21 08:49 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/87a6fa95de0752a086be51489c0681d917e11d03cb82bbe82ea58e085191208e.png) |

2024-06-21 09:02 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/18e10d301e3cfa3bb2446cdc091c2c6d07309c27c249208f3b18175f853ac637.png) |

2024-06-21 09:05 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/387c94a0a5cf6d229477275671dd509c85a36b1c3d3f470b1d87c7af24fc9aef.png) |

2024-06-21 09:13 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/4ef1cd93588f566ec9a73d8280f6f73158de9b71317dd0551b98c82fa5c74bbc.png) |

2024-06-22 15:27 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/387c94a0a5cf6d229477275671dd509c85a36b1c3d3f470b1d87c7af24fc9aef.png) |

2024-06-23 18:10 UTC, deepspace1000 reviewed
Some stuff you should have a look at 😉. If you have questions just ask me.

2024-06-23 18:10 UTC, deepspace1000 commented on frontend/src/components/CreateGrade.tsx
> +        />
I would probaly still go with react hook forms, even thought its arguable if it makes sense for only one input. But it does make validation and error handling easier... So what would you say?

2024-06-23 18:10 UTC, deepspace1000 commented on frontend/src/components/CreateGrade.tsx
> +          <Button onClick={handleModalClose}>Cancel</Button>
just call the on close function directly.

2024-06-23 18:10 UTC, deepspace1000 commented on frontend/src/components/CreateGrade.tsx
> +    <Modal open={isOpen} onClose={handleModalClose}>
call the onClose function directly

2024-06-23 18:10 UTC, deepspace1000 commented on frontend/src/pages/GradePage.tsx
> +  useEffect(() => {
Wrong place 😂. the invalidate query should be called with the useMutation onSuccess.

2024-06-23 18:10 UTC, deepspace1000 commented on frontend/src/pages/GradePage.tsx
> +  useEffect(() => {
Also for the build fail a little tip:
```
Promise.all([
        queryClient.invalidateQueries({
          queryKey: ['gradeList', shoolId],
        }),
```

2024-06-23 18:10 UTC, deepspace1000 commented on frontend/src/pages/GradePage.tsx
> +      </Snackbar>
Move those to the Modal file too

2024-06-23 19:21 UTC, kieranslost commented on frontend/src/components/CreateGrade.tsx
> +  setShowSnackbarError,
ez, i'll try

2024-06-25 19:34 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/3d93b613cf1c9a78bd33dc4f23469abaad0917287787a2d5454912da643327e0.png) |

2024-06-28 10:59 UTC, deepspace1000 approved these changes

2024-06-28 10:59 UTC, deepspace1000 commented on frontend/src/components/CreateGradeDialog.tsx
> +      queryClient.invalidateQueries(['gradeList', schoolId]);
Put the invalidate into the useMutation directly

2024-06-28 10:59 UTC, deepspace1000 commented on frontend/src/components/CreateGradeDialog.tsx
> +        Ein Fehler ist wärend der Kreierung aufgetreten
Beim erstellend der Klasse ist ein Fehler aufgetreten.

2024-06-28 10:59 UTC, deepspace1000 commented on frontend/src/pages/GradePage.tsx
> +        <AlternateButton type="submit" onClick={() => setOpen(!open)}>
You don't need type submit as you don't submit a Form

2024-06-28 10:59 UTC, deepspace1000 commented on frontend/src/pages/GradePage.tsx
> +  justify-items: center;
I think i had a look at it with martin and we decided to leave it for now as this approach comes with its own problems.
@Quintexxx right?

2024-06-28 12:03 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-30 15:36 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-06-30 15:47 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/846b6120c2234ca445cab76a490750736f4a4302dd6cd66944097209696f09ba.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) |

2024-06-30 15:48 UTC, merged