feat(LERN-49): Implemented getAllSchoolsForAdmin endpoint.
learn-track/learnTrack pull request #157
Opened 2024-06-26 17:18 UTC by SleepyPeel

2024-06-26 19:03 UTC, deepspace1000 requested changes
Nice job. mostly some renaming and change of the @GetMapping endpoint.

2024-06-26 19:03 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/school/SchoolResource.kt
> +    @GetMapping("/getAllSchoolsForAdmin")
```suggestion
    @GetMapping(params = ["assignedUserId"])
```

2024-06-26 19:03 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/school/SchoolResource.kt
> +    public fun getAllSchoolsForAdmin(@RequestParam userId: UUID): List<SchoolDto> = schoolService.getAllSchools()
```suggestion
    public fun getSchoolsByUser(@RequestParam userId: UUID): List<SchoolDto> = schoolService.getAllSchools()
```

2024-06-26 19:03 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/school/SchoolService.kt
> +    public fun getAllSchoolsForAdmin(userId: UUID): List<SchoolDto> = schoolDao.fetchAllSchoolsForAdmin(userId).map(
```suggestion
    public fun getSchoolsByUserId(userId: UUID): List<SchoolDto> = schoolDao.fetchAllSchoolsForAdmin(userId).map(
```

2024-06-26 19:04 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/school/SchoolResource.kt
> +    @GetMapping("/getAllSchoolsForAdmin")
@A1eeee Have we used the params like this before here?

2024-06-27 05:39 UTC, A1eeee commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/school/SchoolResource.kt
> +    @GetMapping("/getAllSchoolsForAdmin")
No, we never used it the query params like that before.

2024-06-30 16:21 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/school/SchoolResource.kt
> +    public fun getAllSchoolsForAdmin(@RequestParam userId: UUID): List<SchoolDto> = schoolService.getAllSchools()
FYI you called the wrong schoolService function it's not getAllSchools but getAllSchoolsForAdmin (which should also be renamed.

2024-06-30 16:23 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/school/SchoolResource.kt
> +    @GetMapping("/getAllSchoolsForAdmin")
Okay, there isn't a real difference in doing it like this but documenting it in the @GetMapping annotation. so i would go with my suggestion.

2024-07-01 18:02 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/846b6120c2234ca445cab76a490750736f4a4302dd6cd66944097209696f09ba.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) |

2024-07-02 16:42 UTC, merged