feat(LERN-102): implemented getGradeDetails endpoint
learn-track/learnTrack pull request #158
Opened 2024-06-30 21:24 UTC by A1eeee

Also added column subjectId to tblUser and changed renaming in the frontend.

2024-07-01 10:14 UTC, deepspace1000 requested changes

2024-07-01 10:14 UTC, deepspace1000 commented on backend/src/main/resources/db/changelog/changes/2024-06-29_column_subjectId_tblUser.xml
> +        </addColumn>
do it the other way around. add a column teacher_id to t_subject.

2024-07-01 17:56 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-07-02 18:36 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/846b6120c2234ca445cab76a490750736f4a4302dd6cd66944097209696f09ba.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) |

2024-07-02 18:53 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-07-02 19:44 UTC, deepspace1000 reviewed
i think we can remove some code...

2024-07-02 19:44 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/persistence/SubjectQueries.kt
> +    .from(GRADE)
when you are going from SubjectDao please use .from(SUBJECT)

2024-07-02 19:44 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/subject/SubjectDto.kt
> +    val name: String,
shouldn't this also have gradeId and teacherId?

2024-07-02 19:44 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/subject/SubjectDto.kt
> +    val name: String,
When you add the teacherId you can call in the adminGradeService the get userById function withouth the need to write a query to join user on subject. you can call the default jooy query UserDao.fetchOneByid(teacherId).

2024-07-02 19:44 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/user/UserService.kt
> +    public fun getUserBySubjectId(subjectId: UUID): UserDto? =
should not be needed anymore

2024-07-02 19:44 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/persistence/UserQueries.kt
> +    .fetchOneInto(User::class.java)
should not be needed anymore

2024-07-02 20:13 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/846b6120c2234ca445cab76a490750736f4a4302dd6cd66944097209696f09ba.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/56232751b573832868edb5c01608e8092ca20e9677e074f4da9740a6f9664b21.png) |

2024-07-03 19:28 UTC, deepspace1000 requested changes
Split the Dto up into 2 different apis.

2024-08-24 14:16 UTC, closed without merging