feat(LERN-47): Implemented Teacher and Student count endpoint.
learn-track/learnTrack pull request #162
Opened 2024-07-02 16:31 UTC by SleepyPeel

2024-07-02 17:07 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-07-02 17:08 UTC, deepspace1000 requested changes
Write a test for the getAllAdmin user endpoint

2024-07-02 17:08 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserQueries.kt
> +public fun UserDao.fetchAllAdminsForSchool(schoolId: UUID): MutableList<User> = ctx()
```suggestion
public fun UserDao.fetchAllAdminUserBySchoolId(schoolId: UUID): MutableList<User> = ctx()
```

2024-07-02 17:08 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserQueries.kt
> +public fun UserDao.countTeachersInSchool(schoolId: UUID, userRole: UserRole): Int = ctx()
```suggestion
public fun UserDao.fetchUserCountBySchoolIdAndUserRole(schoolId: UUID, userRole: UserRole): Int = ctx()
```

2024-07-02 17:08 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserResource.kt
> +    //please someone who is smarter than me (me=Shay) fix this
??

2024-07-02 17:08 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserResource.kt
> +    @GetMapping("/getTeacherCounts")
```suggestion
    @GetMapping("/getTeacherCount")
```
at least still don't like it but its okay for the moment.

2024-07-02 17:08 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserResource.kt
> +    @GetMapping("/getStudentCounts")
```suggestion
    @GetMapping("/getStudentCount")
```

2024-07-02 17:08 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserService.kt
> +    public fun getAllAdminsForSchool(schoolId: UUID): List<UserDto> = userDao.fetchAllAdminsForSchool(schoolId).map(
```suggestion
    public fun getAllAdminsBySchoolId(schoolId: UUID): List<UserDto> = userDao.fetchAllAdminsForSchool(schoolId).map(
```

2024-07-03 17:20 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2024-07-03 17:26 UTC, deepspace1000 commented on backend/src/main/kotlin/ch/learntrack/backend/backoffice/user/UserQueries.kt
> +public fun UserDao.fetchAllAdminUserBySchoolId(schoolId: UUID): MutableList<User> = ctx()
```suggestion
public fun UserDao.fetchAllAdminUserBySchoolId(schoolId: UUID): List<User> = ctx()
```

2024-07-03 17:32 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/846b6120c2234ca445cab76a490750736f4a4302dd6cd66944097209696f09ba.png) |

2024-07-03 17:39 UTC, deepspace1000 approved these changes

2024-07-03 17:41 UTC, merged