feat(LERN-72): Added Create Student Modal
learn-track/learnTrack pull request #163
Opened 2024-07-02 17:49 UTC by Quintexxx

2024-07-02 18:51 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/5ed1fbeb0b2621d0021c91f1c9f42c0f29e32571b2ecbc99ec4f06708d106d90.png) |

2024-07-03 10:58 UTC, deepspace1000 requested changes

2024-07-03 10:58 UTC, deepspace1000 commented on frontend/src/components/CreateStudentModal.tsx
> +  const [showSnackbar, setShowSnackbar] = useState(false);
```suggestion
  const [showSuccessSnackbar, setShowSuccessSnackbar] = useState(false);
```

2024-07-03 10:58 UTC, deepspace1000 commented on frontend/src/components/CreateStudentModal.tsx
> +  const [showSnackbarError, setShowSnackbarError] = useState(false);
```suggestion
  const [showErrorSnackbar, setShowErrorSnackbar] = useState(false);
```
you don't show an Error because snackbar is not working you show an error in snackbar (i know Kiearan did it this way but i didn't see it then).

2024-07-03 10:58 UTC, deepspace1000 commented on frontend/src/components/CreateStudentModal.tsx
> +          <Typography level="h3" fontSize={35} marginBottom={2}>
decide between fontSize or level.

2024-07-03 10:58 UTC, deepspace1000 commented on frontend/src/components/StudentRegisterForm.tsx
> +const PASSWORD_REGEX = /^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\w\d\s:])([^\s]){8,}$/;
we don't need the password to reach requirements. as an admin has to create a lot of students so he should be able to set an easy password and then let student change it later.

2024-07-03 10:58 UTC, deepspace1000 commented on frontend/src/components/StudentRegisterForm.tsx
> +  setOpen,
also use an onClose here.

2024-07-03 10:58 UTC, deepspace1000 commented on frontend/src/pages/StudentPage.tsx
> +        <AlternateButton onClick={() => setOpen(!open)}>Schüler hinzufügen</AlternateButton>
```suggestion
        <AlternateButton onClick={() => setOpen(true)}>Schüler hinzufügen</AlternateButton>
```
As we never close the modal over here.

2024-07-03 10:58 UTC, deepspace1000 commented on frontend/src/pages/StudentPage.tsx
> +      </Snackbar>
Thats okay for now, but i guess you could also put them into the modal file.

2024-07-03 18:03 UTC, Quintexxx commented on frontend/src/components/CreateStudentModal.tsx
> +export function CreateStudentModal({ isOpen, setOpen }: { isOpen: boolean; setOpen: (open: boolean) => void }) {
I hope i implemented it the way you did 🙏

2024-07-03 18:26 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/732f698ecda993a03e17bc917099921fefeea73fa2238fbca2bd50fe01c31979.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/5ed1fbeb0b2621d0021c91f1c9f42c0f29e32571b2ecbc99ec4f06708d106d90.png) |

2024-07-04 17:26 UTC, deepspace1000 approved these changes
Remember to not sqash and have different commits after each review so its easier for me to see what you've changed and i so i don't have to look at the whole code again.

2024-07-04 17:29 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ custom/admin-landing-page*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/2c06830cce28066bece69436626b74fdf5be4d65a47460b0cea553102d031789.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clwakk6apmz6tmr0e0522m9di/5ed1fbeb0b2621d0021c91f1c9f42c0f29e32571b2ecbc99ec4f06708d106d90.png) |

2024-07-04 17:54 UTC, merged